name: Rilncraft
main: io.github.jonnyaxehandle.rilncraft.Rilncraft
version: 0.1
commands:
    tpr:
        usage: /tpr [player name]
    marry:
        usage: /marry propose|home [player name]
    friends:
        usage: /friends add|remove [playername]
    accept:
        usage: /accept
    deny:
        usage: /deny
    claim:
        usage: /claim
    unclaim:
        usage: /unclaim
    rankup:
        usage: /rankup
    team:
        usage: /team (create|dispand|invite|kick|promote) (Team|Player)
    divorce:
        usage: /divorce
    rchelp:
        usage: /rchelp [page]
    riln:
        usage: /riln [pay (player name) (amount)]